apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: meu-primeiro-pvc
  name: meu-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
  storageClassName: nfs
  selector:
    matchLabels:
      storage: nfs