apiVersion: v1
kind: Pod
metadata:
  name: bar-app
  labels:
    app: bar
    svc: foo-bar
spec:
  containers:
  - name: bar-app
    image: nginx:1.22.0
    volumeMounts:
    - name: config
      mountPath: /usr/share/nginx/html
      readOnly: true
  volumes:
  - name: config
    configMap:
      name: bar-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bar-config
data:
  index.html: |
    bar
---
apiVersion: v1
kind: Service
metadata:
  name: bar-service
spec:
  selector:
    app: bar
  ports:
  - port: 80