apiVersion: v1
kind: Service
metadata:
  name: my-external-service
spec:
  type: ExternalName
  externalName: htmledit.squarefree.com # Acessível com http://my-external-service ou http://my-external-service.default.svc.cluster.local