apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    name: http
    targetPort: 80
  type: LoadBalancer